### ISSUE TITLE
Can't cast top tv hotbox

### ISSUE THREAD

**Issue by FUNKDATSHhhhhh** [maxi1134/Home-Assistant-Config#41]
Can't cast my videos on hotbox top tv

**Comment by maxi1134** [comment]
The "Chilling Cast" SSID is currently redirecting to the internal LAN instead of the cast LAN. This causes the firewall rules to no longer be applied for the casting.

This will be resolved once I am done testing with the wiim receivers on that SSID

**Comment by maxi1134** [comment]
This seems to persist after a rollback. Only this TV is affected

**Comment by maxi1134** [comment]
Seems fixed after changing some network rules
