### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by Profxmas** [maxi1134/Home-Assistant-Config#57]
Hi,
Great project, what do uou use for camera (harware and software ) ?

**Comment by maxi1134** [comment]
Hi,
Thanks for posting.

The software used for the NVR is this project: 
https://github.com/blakeblackshear/frigate


Be aware that an Intel CPU and a Coral TPU are highly recommended!

**Comment by maxi1134** [comment]
> Hi, Great project, what do uou use for camera (harware and software ) ?

Additionally, you can find the camera list here: https://github.com/maxi1134/Home-Assistant-Config/blob/master/documentation/hardware.md#security-hardware
