### ISSUE TITLE
Perform a web search using the Open WebUI Assistant?

### ISSUE THREAD

**Issue by TheRealPSV** [maxi1134/Home-Assistant-Config#64]
I was looking at the guide to set up Open WebUI as a fallback conversation agent: https://github.com/maxi1134/Home-Assistant-Config/blob/master/documentation/guides/voice_assistance_guide_open_webui.md

Is there a way to have the conversation agent perform a web search and take advantage of the Open WebUI search engine functionality?

**Comment by maxi1134** [comment]
> I was looking at the guide to set up Open WebUI as a fallback conversation agent: https://github.com/maxi1134/Home-Assistant-Config/blob/master/documentation/guides/voice_assistance_guide_open_webui.md
> 
> Is there a way to have the conversation agent perform a web search and take advantage of the Open WebUI search engine functionality?

I've been looking for the same, which was my main goal of using this tool. I will come back when I found how to.

**Comment by maxi1134** [comment]
I've found this in the discord:

```
http://localhost:8080/retrieval/api/v1/docs

The /process/web/search endpoint
```

**Comment by TheRealPSV** [comment]
I decided to make an integration to do it, both direct OpenWebUI conversations and searches: https://github.com/TheRealPSV/ha-openwebui-conversation
